name = "rrbank_api"
main = "src/index.ts"
compatibility_date = "2024-12-05"

compatibility_flags = [ "nodejs_compat_v2" ]

[vars]
# ----------------------------------------------------------------------------- 
# Databse:Docker
# ----------------------------------------------------------------------------- 
DATABASE_URL="postgresql://postgres:mysecretpassword@localhost:3333/postgres"
DATABASE_URL_UNPOOLED="postgresql://postgres:mysecretpassword@localhost:3333/postgres"

#------------------------------------------------------------------------------
# Environment
#------------------------------------------------------------------------------
ENVIRONMENT="development"

[dev]
port = 5000

[observability]
enabled = true
head_sampling_rate = 1

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

